#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  4 22:22:49 2020

@author: sahanaasokan
"""
nums=[1,4,5,6,3]

ya=[n for n in nums]
print(ya)

# I want n^2 for each n
yer= [n*n for n in nums]
print(yer)

#n for each n in nums if n is even, How to create a dictionary
#I want a letter and number pair for each letter in 'abcd' and '1234'

letters=['a','b','c','d']
numbers=[1,2,3,4]
print([(k,v) for k,v in zip(letters,numbers)])


string = ['hello']
print(string)
print([string[i:j] for i in range(len(string)) for j in range(i + 1, len(string) + 1)])


#Getting the index of an item in a list

#Two Pointers

#Linked Lists
#Node has data and a pointer 
#Linked lists have multiple nodes

class Node:
    def __init__(self,value,nextNode=None):
        self.value=value
        self.nextNode=nextNode
        
        
Node1=Node(3)
Node2=Node(5)

Node1.nextNode=Node2






#get_size()
#find(data)
#add(data)
#remove(data)





#Traversing Linked Lists










